sudo: false
language: rust
matrix:
  include:
    - os: windows
      rust: stable

    - os: osx
      rust: stable

    - os: linux
      rust: stable
    - os: linux
      rust: beta
    - os: linux
      rust: nightly

env:
  - RUSTFLAGS="-Ctarget-feature=+aes,+ssse3" RUSTDOCFLAGS="-Ctarget-feature=+aes,+ssse3" RUST_BACKTRACE=1

addons:
  apt:
    packages:
      - libssl-dev

install:
  #- wget https://github.com/jedisct1/libsodium/releases/download/1.0.16/libsodium-1.0.16.tar.gz
  #- tar xvfz libsodium-1.0.16.tar.gz
  #- cd libsodium-1.0.16 && ./configure --prefix=$HOME/installed_libsodium && make && make install && cd ..
  #- export PKG_CONFIG_PATH=$HOME/installed_libsodium/lib/pkgconfig:$PKG_CONFIG_PATH
  #- export LD_LIBRARY_PATH=$HOME/installed_libsodium/lib:$LD_LIBRARY_PATH
  - export SODIUM_BUILD_STATIC=yes

  # Install OpenSSL on Windows
  - if [ "${TRAVIS_OS_NAME}" = "windows" ]; then
    curl -O http://slproweb.com/download/Win64OpenSSL-1_1_0L.exe;
    cmd.exe /C 'Win64OpenSSL-1_1_0L.exe /SILENT /VERYSILENT /SP- /DIR="C:\OpenSSL"';
    export OPENSSL_LIB_DIR=/c/OpenSSL/lib;
    export OPENSSL_INCLUDE_DIR=/c/OpenSSL/include;
    export OPENSSL_DIR=/c/OpenSSL/bin;
    fi

script:
  - cargo test --no-fail-fast --features miscreant
