environment:
    SSL_CERT_FILE: "C:\\OpenSSL\\cacert.pem"

    matrix:
        - TARGET: x86_64-pc-windows-msvc
          BITS: 64
          OPENSSL_VERSION: 1_1_0g
          MSYS2: 1
          OPENSSL_DIR: C:\OpenSSL
          SODIUM_BUILD_STATIC: yes
        # - TARGET: i686-pc-windows-gnu
        #   BITS: 32
        #   OPENSSL_VERSION: 1_1_0g
        #   MSYS2: 1
install:
  - ps: Start-FileDownload "http://slproweb.com/download/Win${env:BITS}OpenSSL-${env:OPENSSL_VERSION}.exe"
  - Win%BITS%OpenSSL-%OPENSSL_VERSION%.exe /SILENT /VERYSILENT /SP- /DIR="C:\OpenSSL"
  - ps: Start-FileDownload "https://curl.haxx.se/ca/cacert.pem" -FileName "C:\OpenSSL\cacert.pem"

  # Install Rust
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init.exe -y --default-host %TARGET%
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - if defined MSYS2 set PATH=C:\msys64\mingw%BITS%\bin;%PATH%

  # Run tests
  - rustc -V
  - cargo -V

build: false

test_script:
    - cargo test -v --no-fail-fast

cache:
    - target
    - C:\Users\appveyor\.cargo\registry
